### PR TITLE
add retries for datastore

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...add-retry-for-datastore-published).

**Comment by tmatsuo** [comment]
Can you resolve the conflict?

**Comment by bshaffer** [comment]
@tmatsuo PTAL

**Comment by bshaffer** [comment]
NM, you LGTM'd the other one.

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
