### PR TITLE
(Really) allow pecl install mongodb to fail.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by bshaffer** [comment]
if the mongo install fails, the unit tests will fail. Why do we want to add this?

**Comment by tmatsuo** [comment]
@bshaffer It fails when the underlining travis image already has the mongodb extension installed. Actually travis image was started to have mongodb.so in their image at some point. I want to be resilient for such changes.

**Comment by bshaffer** [comment]
ok, LGTM

**Comment by tmatsuo** [comment]
Thanks!

**Pull request merged**
