### PR TITLE
[PUBLISHED] 96 - updates apiclient to dev tag

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
LGTM, filed an issue to use stable at #98

**Comment by bshaffer** [comment]
Good call, ty

**Comment by tmatsuo** [comment]
The build will just fail because there is no firewall rule, so I stopped the build.

**Comment by tmatsuo** [comment]
After I merge #95, I will manually add CLOUDSDK_CORE_DISABLE_PROMPTS=1 envvar and restart the build.

**Comment by tmatsuo** [comment]
I restarted the build

**Comment by tmatsuo** [comment]
Alright, I think we can merge this :)

**Pull request merged**
