### PR TITLE
Use php-coveralls phar file from v0.7.0 release.

### PR DESCRIPTION
**Pull request by tmatsuo**
Removed the top level composer.json and started to use the phar file from php-coveralls 0.7.0 release.

A phar file contains all the dependencies, so no need to have composer.json anymore. Tools like php-coveralls often depend on legacy libs, which may conflict with dependencies of modern applications, so it is better to use the phar file.

### CODE REVIEW

**Comment by tmatsuo** [comment]
Oh, wait let me add PHP 7.0 env.

**Comment by tmatsuo** [comment]
Now it's all green :) @bshaffer Can you take a look?

**Comment by tmatsuo** [comment]
@SurferJeffAtGoogle Alright, I added a comment in the script, also updated the PR description.

**Comment by SurferJeffAtGoogle** [comment]
LGTM.

**Comment by tmatsuo** [comment]
@SurferJeffAtGoogle thanks, I will merge this after squashing.

**Pull request merged**
