### PR TITLE
Fixes worker.yaml and removes worker.yaml/app.yaml in GKE tutorial

### PR DESCRIPTION
**Pull request by bshaffer**
merges #142 and runs tests / misc other fixes

### CODE REVIEW

**Comment by bshaffer** [comment]
@thebrubaker please comment and confirm you are aware I'll be committing your change by saying "I consent"

**Comment by tmatsuo** [comment]
LGTM

**Comment by thebrubaker** [comment]
I consent

**Comment by tmatsuo** [comment]
@thebrubaker Thanks for finding the bug!

**Comment by thebrubaker** [comment]
Thanks for the great tutorials + documentation

**Pull request merged**
