### PR TITLE
[PUBLISHED] 108 - Added an instance_tag.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by bshaffer** [comment]
Why is this tagged specifically for mongo? Doesn't that apply to the whole app and not just the mongo instance?

**Comment by tmatsuo** [comment]
Good point, I've just changed the tag name to bookshelf-e2e

**Comment by tmatsuo** [comment]
OK to merge?

**Comment by bshaffer** [comment]
LGTM!

**Pull request merged**
