### PR TITLE
adds logged in test

### PR DESCRIPTION
**Pull request by bshaffer**
Adds logged in test and testing webhooks

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...master-add-login-tests).

**Comment by tmatsuo** [comment]
LGTM

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...master-add-login-tests).

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...master-add-login-tests).

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...master-add-login-tests).

**Pull request merged**
