### PR TITLE
Test improvements.

### LINKED ISSUE #99: Fix too long test
Recently the tests take very long time, we need to fix this

### PR DESCRIPTION
**Pull request by tmatsuo**
Fixes #99 and #101

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...test-improvements-published).

**Comment by tmatsuo** [comment]
Oops there's a conflict, what's the easiest way to fix this? Maybe I can create another PR...

**Comment by bshaffer** [comment]
@tmatsuo I resolved them! Here is what I did:

```
$ git checkout tutorial_steps
$ git pull origin tutorial_steps # (just to be sure)
$ git checkout test-improvements
$ git rebase tutorial_steps
# fix conflict, which was just the "sha" in _tuts/steps.json, and I'm going to fix that issue
$ git rebase --continue
$ git push origin test-improvements -f
```

**Comment by tmatsuo** [comment]
@bshaffer Great thanks!

**Comment by tmatsuo** [comment]
I'm wondering what the sha value is for? Is it just OK to use our sha value (the sha value in my head)?

**Comment by bshaffer** [comment]
@tmatsuo the `sha` is a squirrelly beast.

It is supposed to point to the previous commit of `tutorial_steps`. So if you ever change it, you would do `git log`, pick the second commit down, change the `sha` to it, and then do a `git add _tuts/steps.json` and `git ci --amend` so that HEAD still points to the previous sha.

**Comment by tmatsuo** [comment]
@bshaffer It's still difficult for me, but thanks for the explanation.

**Pull request merged**
