### PR TITLE
uses silex sessions when logged in

### PR DESCRIPTION
**Pull request by bshaffer**
PR for published changes: #44

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...issue-41-use-silex-session-handler-published).

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...issue-41-use-silex-session-handler-published).

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...issue-41-use-silex-session-handler-published).

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
