### PR TITLE
remove manual scaling config

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by tmatsuo** [comment]
BTW, the test doesn't work for PR from other repo right now. Maybe I should skip the test in that case.

**Comment by tmatsuo** [comment]
Ok, I'm fine with this

**Comment by JustinBeckwith** [comment]
What would it take to get tests to run on forks?  @jmdobry have you figured this out in node land?

**Comment by tmatsuo** [comment]
See TRAVIS.md for running tests on your project (you can run push hook). There is no solution for achieving both; running test suite for PR from other repo, and keeping the secrets.

**Pull request merged**
