### PR TITLE
Adds directories

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
I don't think the test will pass. Now each directory has its own `.travis.yml`, but there should be one in the top level.

**Comment by bshaffer** [comment]
@tmatsuo I will remove those.

**Comment by bshaffer** [comment]
I suppose since each step is supposed to be taken as a standalone app, it's ok to have travis files in each directory. What do you think?

**Comment by tmatsuo** [comment]
Travis doesn't look at them, so those are nothing to do with our test run. I would remove them.

**Comment by bshaffer** [comment]
closing in favor of #30 so we can run tests

**Pull request closed without merging**
