### PR TITLE
Use SetUp instead of SetUpBeforeClass for code coverage.

### LINKED ISSUE #7: Increase the unittest coverage
Now it's under 90%

### PR DESCRIPTION
**Pull request by tmatsuo**
Fixes #7

### CODE REVIEW

**Comment by bshaffer** [comment]
LGTM

**Comment by tmatsuo** [comment]
Thx!

**Comment by bshaffer** [comment]
nit: we should branch from our own forks of the repo rather than from the origin

**Comment by tmatsuo** [comment]
agreed, will use my fork

**Pull request merged**
