### PR TITLE
[PUBLISHED] 78 - update google/api-client to RC5

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
LGTM

**Comment by tmatsuo** [comment]
In order for the test to pass, we need to pick #82

**Comment by tmatsuo** [comment]
One more thing to consider, we'll need https://github.com/google/google-api-php-client/pull/848 so I hope you'll tag that repo, and we'll need one more update anyways, so how about to make another PR for updating to RC6?

**Comment by tmatsuo** [comment]
I'm fine with merging this though

**Comment by bshaffer** [comment]
We will have to wait before tagging `RC6`, so I'd rather just update once the tag exists.  I'll merge this once the tests pass.

**Comment by tmatsuo** [comment]
Let me merge this

**Pull request merged**
