### PR TITLE
Use AppEngineFlexHandler on prod

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
lgtm

**Comment by tmatsuo** [comment]
Thanks @JustinBeckwith 
I'm also running the full test suite (including deployment e2e tests) on our jenkins server. I will merge this once it passes.

**Comment by bshaffer** [comment]
this looks great!

**Comment by tmatsuo** [comment]
Thanks guys. Merging.

**Pull request merged**
