### PR TITLE
adds _tuts steps to master

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
LGTM

**Comment by tmatsuo** [comment]
Basically I'm all for the change. I'm wondering though, why this _tuts dir doesn't contain the same files as the current tutorial_steps? Will you add the diffs later?

**Comment by bshaffer** [comment]
I coped the files over from tutorial_steps, so it is the same! Are you
seeing something differently?

**Comment by tmatsuo** [comment]
Oh I see. LGTM

**Pull request merged**
