### PR TITLE
remove gitignore and README from start step

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...remove-gitignore-and-readme-from-start-step-published).

**Comment by bshaffer** [comment]
This essentially just makes the starting directory clean. This is a precursor to using `master` as the starting step (changes I am making to the tutorial tooling)

**Comment by tmatsuo** [comment]
LGTM, but why the webhook publishing doesn't work for it?

**Comment by bshaffer** [comment]
I deleted it (sorry) because it doesn't have any changes for the published branch, since I basically just reordered the diff.

**Pull request merged**
