### PR TITLE
fixes cs

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...fix-cs-published).

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...fix-cs-published).

**Comment by tmatsuo** [comment]
LGTM

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...fix-cs-published).

**Pull request merged**
