### PR TITLE
Added PHP 5.6, and composer clean-ups

### PR DESCRIPTION
**Pull request by tmatsuo**
I wanted to add PHP 5.6 explicitly. Also I did composer cleanups (alphabetical order).

### CODE REVIEW

**Comment by bshaffer** [comment]
These changes have been published! View these changes [here](https://github.com/GoogleCloudPlatform/getting-started-php/compare/master...composer-cleanup-published).

**Comment by bshaffer** [comment]
So, `^5.5` actually includes PHP 5.6, which is why I left it that way. I don't mind this though, because it's explicit.

**Comment by bshaffer** [comment]
see the [composer documentation](https://getcomposer.org/doc/articles/versions.md#caret) for more info

**Comment by bshaffer** [comment]
If you want to be explicit, the correct composer use would be `~5.5.0|~5.6.0|~7.0.0`, which essentially means "anything between `5.5.0` and < `5.6.0`, anything between `5.6.0 and < 5.7.0`, and anything between `7.0.0 and < 7.1.0`"

**Comment by tmatsuo** [comment]
Alright, thanks, done. PTAL @bshaffer

**Comment by bshaffer** [comment]
LGTM!

**Pull request merged**
